project:
  type: website

website:
  title: "Aleatoric Considerations"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: about.qmd
        text: "About"
      - href: posts.qmd
        text: "Blog"

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: source

