project:
  type: website

website:
  title: "Costello's Travelling Thought Caravan"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: about.qmd
        text: "About"
      - href: posts.qmd
        text: "Goods"

format:
  html:
    theme: lux
    css: styles.css
    toc: true
    
comments:
  giscus:
    repo: acostello34/portfolio

editor: source

